[package]
name = "hearth"
description = "The Hearth game binary: launcher, main loop and settings."
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "hearth"
path = "src/main.rs"

[dependencies]
hearth_core.workspace = true
hearth_content.workspace = true
hearth_env.workspace = true
hearth_input.workspace = true
hearth_math.workspace = true
hearth_world.workspace = true
hearth_worldgen.workspace = true
hearth_texgen.workspace = true
hearth_render.workspace = true
anyhow.workspace = true
glam.workspace = true
rayon.workspace = true
rustc-hash.workspace = true
wgpu.workspace = true
log.workspace = true
env_logger.workspace = true
winit.workspace = true
directories.workspace = true

[lints]
workspace = true
