[package]
name = "hearth_render"
description = "wgpu renderer: terrain, LOD, entities, sky, water, clouds, weather and post-processing."
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
hearth_ui.workspace = true
hearth_character.workspace = true
hearth_flora.workspace = true
hearth_core.workspace = true
hearth_math.workspace = true
hearth_world.workspace = true
hearth_smooth.workspace = true
hearth_texgen.workspace = true
rustc-hash.workspace = true
smallvec.workspace = true
png.workspace = true
wgpu.workspace = true
winit.workspace = true
glam.workspace = true
bytemuck.workspace = true
log.workspace = true
thiserror.workspace = true
pollster.workspace = true

[dev-dependencies]
hearth_content.workspace = true

[lints]
workspace = true
